# Generated by Django 3.0.6 on 2020-06-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(default=None, max_length=100)),
                ('choice2', models.CharField(default=None, max_length=100)),
                ('choice3', models.CharField(default=None, max_length=100)),
                ('choice4', models.CharField(default=None, max_length=100)),
                ('answer', models.CharField(default=None, max_length=100)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Question')),
            ],
        ),
    ]
