# Generated by Django 3.0.6 on 2020-06-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='que',
            new_name='question',
        ),
    ]
