# Generated by Django 3.0.6 on 2020-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_auto_20200609_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='level',
            name='score',
            field=models.IntegerField(default=0, max_length=2500),
        ),
    ]
