# Generated by Django 3.0.6 on 2020-06-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_auto_20200609_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='level',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
